{
 "title": "Radix Node Dashboard (Multi Job)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Versions / Second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(info_counters_sync_target_state_version{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (info_counters_sync_target_current_diff{job=\"$job\"} / info_counters_sync_target_state_version{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "info_counters_time_duration{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "% Synced",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (info_counters_sync_target_current_diff{job=\"$job\"} / info_counters_sync_target_state_version{job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodeinfo{job=\"$job\"}",
     "legendFormat": "{{ branch_and_commit }}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "View In Epoch",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 18, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "info_epochmanager_currentview_view{job=\"$job\"}",
       "legendFormat": "View"
      }
     ]
    },
    {
     "title": "Epoch",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "info_epochmanager_currentview_epoch{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Address",
     "type": "stat",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nodeinfo{job=\"$job\"}",
       "legendFormat": "{{ owner_address }}"
      }
     ]
    },
    {
     "title": "Registered Validator",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nodeinfo{validator_registered=\"true\", job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Validator Address",
     "type": "stat",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nodeinfo{job=\"$job\"}",
       "legendFormat": "{{ own_validator_address }}"
      }
     ]
    },
    {
     "title": "Node Key",
     "type": "stat",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nodeinfo{job=\"$job\"}",
       "legendFormat": "{{ key }}"
      }
     ]
    },
    {
     "title": "Validator Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nodeinfo{is_in_validator_set=\"true\", job=\"$job\"}"
      }
     ]
    },
    {
     "title": "XRD Balance",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "balance_xrd{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "XRD Staked",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 9, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "validator_total_stake{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Mempool Size",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 18, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "info_counters_mempool_count{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Mempool Additions / Second",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(info_counters_mempool_add_success{job=\"$job\"}[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Radix Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Peers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "total_peers{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Network Peers Over Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "total_peers{job=\"$job\"}",
       "legendFormat": "Peers"
      }
     ]
    },
    {
     "title": "Network Validators",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "total_validators{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Network Validators Over Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "total_validators{job=\"$job\"}",
       "legendFormat": "Validators"
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "processcpuload{job=\"$job\"}",
     "legendFormat": "Process CPU Load"
    },
    {
     "expr": "systemcpuload{job=\"$job\"}",
     "legendFormat": "System CPU Load"
    }
   ]
  },
  {
   "title": "Heap Memory Usage Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "heapmemoryusage_max{job=\"$job\"}",
     "legendFormat": "Maximum Heap Size"
    },
    {
     "expr": "heapmemoryusage_used{job=\"$job\"}",
     "legendFormat": "Used Heap Size"
    }
   ]
  },
  {
   "title": "Heap Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(heapmemoryusage_used{job=\"$job\"} / heapmemoryusage_max{job=\"$job\"}) * 100",
     "legendFormat": "used"
    },
    { "legendFormat": "max" }
   ]
  }
 ]
}